### ISSUE TITLE
addCounter: IndexOutOfBounds 1 of 1 - 211.6.9 - 1.21.1

### ISSUE THREAD

**Issue by Yellowsam4145** [mrbuilder1961/WheresMyChatHistory#211] opened 2024-12-03 01:45 UTC
### Description
Simply logged onto my favororite server, testing something, then checked the logs, and noticed a message to report this bug

### How to reproduce
Logged on to a server called DiamondFire, 1 visible side effect noticed, older messages don't have the dupe counter

### Expected result
I expected the side effect to be that the chat's dupe counter wouldn't work at all

### Log file link
https://mclo.gs/RJrUzkw

### Specs and Details
Required information:
- Windows 11
- 6.9 (Nice)
- Quilt: 0.27.0, Fabric API: 0.108.0, and YetAnotherConfigLib: 3.6.1
- Mod Menu: 11.0.3

### Additional context
Seems like a very minor issue, but the log said to report it

**Comment by mrbuilder1961** [comment] 2024-12-03 03:13
thanks for the report, could you also attach your chatlog.json file and name a message or two that should have a dupe counter but dont? i thought i fixed this but i mightve overlooked another critical part.

**Comment by Yellowsam4145** [comment] 2024-12-05 02:10
Sadly, I do not have it, I updated to 1.21.3

**Comment by mrbuilder1961** [comment] 2024-12-05 02:59
so did the bug go away too?

**Comment by mrbuilder1961** [comment] 2024-12-17 03:16
going to close this as unreproduceable, if it still persists in the latest version (>=214.6.10) then please reopen it and give more information!

**Closed as not planned** 2024-12-17 03:17 UTC
Labels: bug, awaiting info
