### ISSUE TITLE
Bug summary - Mod version - MC version

### ISSUE THREAD

**Issue by nightecy** [mrbuilder1961/WheresMyChatHistory#201] opened 2024-09-12 11:15 UTC
### Description
everytime i try to join a server with the mod installed, it takes a while and sometimes starts up and other times it just crashes my game, it tells me to add more to my game, but i have 8 gigs allocated and normally only use like 3-4, even if the mod takes 3 gigs it still shouldnt crash.

heres a video of it: https://youtu.be/8XbmEaH2yGw

### How to reproduce
start up minecraft and join a server

### Expected result
join the minecraft server

### Log file link
all it gives me is this link: https://bugs.mojang.com/browse/MC-23484

and says this:
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.
This crash may be resolved by allocating additional memory in the configuration for this version of Minecraft: Java Edition.
Exit code -805306369

### Specs and Details
Required information:
- windows 10, i7-4790k 4GHz, 16 gigs of ram, doodo ah gpu ( intel(R) HD graphics 4600) | now before you diss the pc, it runs everything els normally it only crashes with the mod! (no diss to the mod i rly like it, the bug is a bit anoyyin tho).

- mod version: 211.6.7
- Fabric (loader verison: 0.15.11-1.21), Fabric API (0.100.6+1.21), and YetAnotherConfigLib (3.5.0+1.21)
- Mod Menu (11.0.1)

Optional but suggested information:
- `chatpatches.json` file: 
[chatpatches.json](https://github.com/user-attachments/files/16978091/chatpatches.json)

- `chatlog.json` file:  
[chatlog.json](https://github.com/user-attachments/files/16978098/chatlog.json)

and i also have a 3rd one (idk if this one matters buuuuuut: 
[chatlog_2024-08-30_17-34-18.json](https://github.com/user-attachments/files/16978106/chatlog_2024-08-30_17-34-18.json)

### Additional context
👍

**Comment by mrbuilder1961** [comment] 2024-09-12 12:23
sounds like a dupe of #191, but please attach your latest.log file on https://mclo.gs here!

**Closed as not planned** 2024-09-12 12:23 UTC
Labels: bug

**Comment by nightecy** [comment] 2024-09-12 13:10
o mb
also heres the latest.log file (i normally have mod menu installed for the video example i didnt tho): https://mclo.gs/4UWA1b5
