### ISSUE TITLE
Translate message feature

### ISSUE THREAD

**Issue by nenamoree9** [mrbuilder1961/WheresMyChatHistory#213] opened 2024-12-25 05:11 UTC
When I want to translate chat messages to see what they say, I have to go to my browser, search up translate and paste the message. It's super frustrating. But this can be fixed by adding a simple but handy chat message translate feature.

You can translate messages by right clicking them to access the context menu, and click on the "Translate" option or click on the language icon in the top right hand corner of the screen.. You can either choose to display it or copy it to your clipboard. This makes things more easier when translating messages.

An alternative option is to translate only the actual message and not the timestamp. This could also be accessed via the Translate context menu.

![example](https://github.com/user-attachments/assets/16c8291c-7e01-4f47-a91f-3d6b85e7de60)
Here's an example of what it may look like. I know the translate icon is not there because it's off the image. You may probably do better than me or add more options.

**Comment by mrbuilder1961** [comment] 2024-12-25 06:05
duplicate of #188, but i appreciate the image example! i'll try to prioritize this when i can 🙃

**Closed as duplicate** 2024-12-25 06:05 UTC
Labels: suggestion

**Comment by nenamoree9** [comment] 2024-12-25 23:13
@mrbuilder1961 why is it not planned?

**Comment by mrbuilder1961** [comment] 2024-12-25 23:40
this is a duplicate, it's still planned but it will be documented under the original issue

**Comment by nenamoree9** [comment] 2024-12-26 02:15
got it i just didn't know that it was duped until i came to the issues section and saw another suggestion on the same thing xD

**Comment by nenamoree9** [comment] 2024-12-26 02:16
i spent like 30 mins on the image lol
