### ISSUE TITLE
Add moving search box to top of the chat box

### ISSUE THREAD

**Issue by Tetro48** [mrbuilder1961/WheresMyChatHistory#182] opened 2024-07-03 08:09 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (ex. I'm always frustrated when [...])
There are people who'd use Wynntils and ChatPatches together, and this GUI collision makes it messy, and I'm one of them now.
![image](https://github.com/mrbuilder1961/ChatPatches/assets/76738929/0ed1f561-58c9-49fa-88f3-992e42683733)

**Describe the solution you'd like**
A clear and detailed description of what you want to happen.
Add the option to move the search box to top in config.

**Describe alternatives you've considered**
Not yet.

**Additional context**

**Comment by mrbuilder1961** [comment] 2024-07-03 14:36
you could click on the search button to hide the search field, if you wanted to temporarily prevent the overlap. however, this is a dupe of #114.

**Closed as not planned by mrbuilder1961** 2024-07-03 14:36 UTC
Labels: suggestion
