### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by t0mtee** [mrbuilder1961/WheresMyChatHistory#26] opened 2022-08-22 15:01 UTC
Quilt, 1.19, 1.51
[Log](https://mclo.gs/ofzNoJi)

**Comment by mrbuilder1961** [comment] 2022-08-23 12:10
Warning: I don't know much about Quilt and am not sure if it is compatible with Fabric mods, so it could just be incompatible but i'll look into this anyway.

**Comment by t0mtee** [comment] 2022-08-23 12:23
The majority of Fabric mods should be compatible with Quilt, and if they're not, it should be pretty easy to get them to work. Thanks for looking into it.

**Comment by SplendidAlakey** [comment] 2022-08-24 09:47
Has nothing to do with Quilt, you are using No Chat Reports and this mod already disables chat reports so they are incompatible.

**Comment by mrbuilder1961** [comment] 2022-08-24 11:10
No that's not the problem, this mod is supposed to have NCR integration. The problem is with the essentials mod, it has a new chat feature and whenever another mod also modifies the chat Minecraft tends to blame me for the mixin error. I thought i fixed this by setting my mods to a higher priority but i guess not.

**Comment by SplendidAlakey** [comment] 2022-08-24 11:18
Ah, my bad. There's another open issue where a person is crashing with NCR and I've seen another crash with WMCH and NCR on reddit, hence my assumption.

Good to know the mods should be compatible.

**Comment by mrbuilder1961** [comment] 2022-08-24 14:47
My apologies, that message was misleading. They are compatible, but i think i implemented it incorrectly so if you don't have them both installed it crashes.

**Comment by SidOfThe7Cs** [comment] 2022-08-24 20:37
mine is also crashing, i tried turning of essentials and/or installing no chat reporting but neither worked

**Comment by mrbuilder1961** [comment] 2022-08-24 22:13
Okay so update on the root issue of this report: it's crashing because another mod (essentials) is also trying to modify the chat interface. I unfortunately don't have much control over that, but I'll mark it as incompatible with this mod. In the meantime, remove Essentials and you should keep NoChatReports as well to make sure it loads.

**Comment by SidOfThe7Cs** [comment] 2022-08-25 22:09
so it does work now that i uninstalled essantialls and installed no chat reports, but i am noticing that when i try to click on something in chat it only works if i click a bit below and to the left of what i want to click on

**Comment by mrbuilder1961** [comment] 2022-08-27 15:11
I think I just fixed that bug, but if you want feel free to post a photo/gif of it just in case.

**Comment by mrbuilder1961** [comment] 2022-08-27 22:39
Should have been fixed by [this](https://github.com/mrbuilder1961/WheresMyChatHistory/commit/d6865b49402306a620d257a4d42b41c50826cbb5) commit, forgot to mark it as such when I pushed it.

**Closed as completed by mrbuilder1961** 2022-08-27 22:39 UTC
Labels: bug

**Comment by t0mtee** [comment] 2022-08-27 22:49
I will try it next time I have the chance, thanks
