### ISSUE TITLE
Xaero's Minimap Waypoint Sharing Messages are Blank (v204.6.4-1.20.4 Fabric)

### ISSUE THREAD

**Issue by iblowmymind** [mrbuilder1961/WheresMyChatHistory#158] opened 2024-04-12 13:02 UTC
### Description
When someone shares a waypoint using Xaero's Minimap, normally it's supposed to display a custom chat message with an add button. The minimap mod accomplishes this with intercepting messages that begin with "xaero-waypoint:" and replacing it with its custom message. However, with Chat Patches, the message will just show up as blank space.

### How to reproduce
1. Install Xaero's Minimap, World Map (optional?) and Chat Patches.
2. Have someone else in multiplayer create a waypoint and share it.
3. The message will be blank.

### Expected result
The chat message should say the waypoint's name, and have an [Add] button that adds the waypoint.

### Log file link
```log4j
[14:20:59] [Render thread/ERROR]: [ChatUtils.modifyMessage] An error occurred while modifying message 'TestUser shared a waypoint called "Cave" from overworld! §2§n[Add]', returning original:
[14:20:59] [Render thread/ERROR]: [ChatUtils.modifyMessage] /!\ Please report this error on GitHub or Discord with the full log file attached! /!\
java.lang.IllegalStateException: No closing angle bracket found in vanilla message 'TestUser shared a waypoint called "Cave" from overworld! §2§n[Add]' !
	at obro1961.chatpatches.util.ChatUtils.lambda$modifyMessage$3(ChatUtils.java:224) ~[chatpatches-204.6.4.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at obro1961.chatpatches.util.ChatUtils.modifyMessage(ChatUtils.java:224) ~[chatpatches-204.6.4.jar:?]
	at net.minecraft.class_338.localvar$zko000$chatpatches$modifyMessage(class_338.java:688) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_1815(class_338.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_44811(class_338.java:211) ~[client-intermediary.jar:?]
	at net.minecraft.class_338.method_1812(class_338.java:206) ~[client-intermediary.jar:?]
	at xaero.common.minimap.waypoints.WaypointSharingHandler.onWaypointReceived(WaypointSharingHandler.java:97) ~[Xaeros_Minimap_24.0.3_Fabric_1.20.4.jar:?]
	at xaero.common.events.ClientEvents.handleChatMessage(ClientEvents.java:161) ~[Xaeros_Minimap_24.0.3_Fabric_1.20.4.jar:?]
	at xaero.common.events.ClientEvents.handleClientSystemChatReceivedEvent(ClientEvents.java:154) ~[Xaeros_Minimap_24.0.3_Fabric_1.20.4.jar:?]
	at xaero.common.core.XaeroMinimapCore.onSystemChat(XaeroMinimapCore.java:280) ~[Xaeros_Minimap_24.0.3_Fabric_1.20.4.jar:?]
	at net.minecraft.class_7594.handler$flg000$xaerominimap$onHandleSystemChat(class_7594.java:2039) ~[client-intermediary.jar:?]
	at net.minecraft.class_7594.method_44736(class_7594.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_43596(class_634.java:869) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_43631(class_7439.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_11054(class_7439.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

### Specs and Details
- Windows 10 Pro 22H2
- ChatPatches v204.6.4 for Fabric 1.20.4
- Minecraft 1.20.4, Fabric Loader 0.15.9, Fabric API 0.97.0
- YACL 3.3.2, Mod Menu 9.1.0-beta.1
- List of mods:
```
  [✔] AmbientSounds_FABRIC_v5.3.5_mc1.20.4
  [✔] amecs-1.3.11+mc.1.20.4
  [✔] animatica-0.6+1.20
  [✔] appleskin-fabric-mc1.20.3-2.5.1
  [✔] architectury-11.1.17-fabric
  [✔] arrp-0.8.1
  [✔] Axiom-2.7.0-for-MC1.20.4
  [✔] badpackets-fabric-0.6.1
  [✔] bettermounthud-1.2.2
  [✔] BetterPingDisplay-Fabric-1.20.4-1.1.1
  [✔] BetterThirdPerson-Fabric-1.20-1.9.0
  [✔] blur-3.2.0
  [✔] bobby-5.1.0+mc1.20.4
  [✔] capes-1.5.3+1.20.2-fabric
  [✔] chatpatches-204.6.4
  [✔] citresewn-1.1.5+1.20.4
  [✔] cloth-config-13.0.121-fabric
  [✔] completeconfig-2.5.3
  [✔] continuity-3.0.0-beta.4+1.20.2
  [✔] CreativeCore_FABRIC_v2.11.16_mc1.20.4
  [✔] cubes-without-borders-1.1.0+1.20
  [✔] Debugify-1.20.4+1.1
  [✔] DisableCustomWorldsAdvice-5.0
  [✔] dynamiccrosshair-7.7+1.20.4-fabric
  [✔] dynamic-fps-3.4.2+minecraft-1.20.4-fabric
  [✔] e4mc-4.0.1+1.19.4-fabric
  [✔] enhancedblockentities-0.9.1+1.20.2
  [✔] entity_model_features_fabric_1.20.4-1.3
  [✔] entity_texture_features_fabric_1.20.4-5.2.3
  [✔] entityculling-fabric-1.6.4-mc1.20.4
  [✔] essential_1-3-1-3_fabric_1-20-4
  [✔] fabric-api-0.97.0+1.20.4
  [✔] fabric-language-kotlin-1.10.19+kotlin.1.9.23
  [✔] fabrishot-1.12.1
  [✔] fallingleaves-1.15.6+1.20.1
  [✔] ferritecore-6.0.3-fabric
  [✔] freecam-fabric-1.2.3+1.20.4
  [✔] Gamma-Utils-1.7.19-mc1.20.4
  [✔] ImmediatelyFast-Fabric-1.2.11+1.20.4
  [✔] indium-1.0.30+mc1.20.4
  [✔] iris-mc1.20.4-1.6.17
  [✔] itemswapper-fabric-0.5.6-mc1.20.4
  [✔] kirin-1.17.1+1.20.4
  [✔] krypton-0.2.6
  [✔] lambdynamiclights-2.3.4+1.20.4
  [✔] litematica-fabric-1.20.4-0.17.2
  [✔] lithium-fabric-mc1.20.4-0.12.1
  [✔] malilib-fabric-1.20.4-0.18.1
  [✔] minihud-fabric-1.20.4-0.30.2
  [✔] mixintrace-1.1.1+1.17
  [✔] modernfix-fabric-5.15.0+mc1.20.4
  [✔] modmenu-9.1.0-beta.1
  [✔] moreculling-1.20.4-0.22.1
  [✔] mousewheelie-1.13.3+mc1.20.4
  [✔] NoChatReports-FABRIC-1.20.4-v2.5.0
  [✔] NoFog-1.3.5+1.16.5-1.20.4
  [✔] notenoughanimations-fabric-1.7.1-mc1.20.4
  [✔] PresenceFootsteps-1.11.3
  [✔] puzzle-1.6.1+1.20.4
  [✔] reeses_sodium_options-1.7.2+mc1.20.4-build.102
  [✔] RoughlyEnoughItems-14.0.692-fabric
  [✔] skinlayers3d-fabric-1.6.2-mc1.20.4
  [✔] sodium-extra-0.5.4+mc1.20.4-build.116
  [✔] sodium-fabric-0.5.8+mc1.20.4
  [✔] sound-physics-remastered-fabric-1.20.4-1.3.1
  [✔] status-effect-bars-1.0.4
  [✔] tweakeroo-fabric-1.20.4-0.19.2
  [✔] viafabricplus-3.1.0
  [✔] voicechat-fabric-1.20.4-2.5.12
  [✔] worldedit-mod-7.3.0
  [✔] wthit-fabric-10.5.0
  [✔] Xaeros_Minimap_24.0.3_Fabric_1.20.4
  [✔] XaerosWorldMap_1.38.1_Fabric_1.20.4
  [✔] yet-another-config-lib-fabric-3.3.2+1.20.4
```
### Additional context
- Example message from chatlog.json:
```
    {
        "text": "",
        "extra": [
        {
            "text": "[16:01:47] ",
            "hoverEvent":
            {
                "contents":
                {
                    "text": "11/04/2024",
                    "obfuscated": false,
                    "italic": false,
                    "underlined": false,
                    "strikethrough": false,
                    "color": "#FFFFFF",
                    "bold": false
                },
                "action": "show_text"
            },
            "insertion": "1712840507517",
            "obfuscated": false,
            "clickEvent":
            {
                "action": "suggest_command",
                "value": "11/04/2024"
            },
            "italic": false,
            "underlined": false,
            "strikethrough": false,
            "color": "#FF55FF",
            "bold": false
        },
        {
            "text": "",
            "hoverEvent":
            {
                "contents": "468, 65, -397",
                "action": "show_text"
            },
            "clickEvent":
            {
                "action": "run_command",
                "value": "/xaero_waypoint_add:Cave:C:468:65:-397:11:false:0:Internal_overworld_waypoints"
            },
            "color": "gray"
        }, ""],
        "hoverEvent":
        {
            "contents": "468, 65, -397",
            "action": "show_text"
        },
        "clickEvent":
        {
            "action": "run_command",
            "value": "/xaero_waypoint_add:Cave:C:468:65:-397:11:false:0:Internal_overworld_waypoints"
        },
        "color": "gray"
    },
```

- What the waypoint messages look like from the server side:
```
xaero-waypoint:Cave:C:468:65:-397:11:false:0:Internal_overworld_waypoints
```

Thanks!

**Comment by iblowmymind** [comment] 2024-04-14 08:40
In hindsight, this issue is pretty similar to #156. I should've looked better before creating the issue, I just searched for Xaero and saw nothing so I thought it would be okay. Apologies!
Trying out the included test build you linked in that issue, though, does not fix the problem for me. The error message returned in the log is the exact same.

**Comment by mrbuilder1961** [comment] 2024-04-14 16:00
no it's okay, this likely has a slightly different root cause that just happens to be causing the same outcome. i'll try and provide a different test build later to see what's up, but it seems like the xaero chat message is being marked as a vanilla-formatted one, which breaks the existing code bc it isn't actually formatted that way. i'll see what i can do!

also, tysm for the detailed report! it's so organized and it almost makes me want to keep it up lmao

**Comment by mrbuilder1961** [comment] 2024-04-14 22:35
i doubt this will fix the issue, but if you could try loading this and sending the log that would be great! just make sure to try and reproduce the issue again before sending the log. https://cdn.discordapp.com/attachments/901476441080860672/1229197816513958008/chatpatches-204.6.5.jar?ex=662eceac&is=661c59ac&hm=4c4437fd2aef22968873f7e6e257bd35c9f66574f5070dfa0e983ae5c4db8d0c&

**Comment by BlueJayofEvil** [comment] 2024-04-21 00:59
> i doubt this will fix the issue, but if you could try loading this and sending the log that would be great! just make sure to try and reproduce the issue again before sending the log. https://cdn.discordapp.com/attachments/901476441080860672/1229197816513958008/chatpatches-204.6.5.jar?ex=662eceac&is=661c59ac&hm=4c4437fd2aef22968873f7e6e257bd35c9f66574f5070dfa0e983ae5c4db8d0c&

I'm also having the same issue, so I tried with that build you linked. Still not fixed.
Here's my logs: https://mclo.gs/dPI7eY1

**Comment by Hlebuw3k** [comment] 2024-08-08 05:01
I have a similar issue where messages from a Discord integration mod don't have their "From Discord" prefix anymore, and appear as normal player messages instead. I think it's caused by the same source, most likely something to do with player name or text formatting. I would like to use this mod, but these issues are preventing me from doing so.

**Comment by mrbuilder1961** [comment] 2024-08-08 12:54
> I have a similar issue where messages from a Discord integration mod don't have their "From Discord" prefix anymore, and appear as normal player messages instead. I think it's caused by the same source, most likely something to do with player name or text formatting. I would like to use this mod, but these issues are preventing me from doing so.

which mod specifically? do you have a log link?

**Comment by Hlebuw3k** [comment] 2024-08-09 09:53
I think it's this mod
https://www.curseforge.com/minecraft/mc-mods/disfabric-and-disforge
I installed ChatPatches again and sent a few messages, here's the logs
[latest.log](https://github.com/user-attachments/files/16559470/latest.log)
[chatlog.json](https://github.com/user-attachments/files/16559471/chatlog.json)
In-game they appear as
`[time] <Hlebuw3k> test (x2)`

**Comment by mrbuilder1961** [comment] 2024-08-09 13:47
https://mclo.gs

**Comment by Trcmoe** [comment] 2024-08-19 03:30
I tried this in singleplayer and got the same result. Here is the log https://mclo.gs/zSgUSUn

**Comment by mrbuilder1961** [comment] 2024-09-19 00:53
could someone try reproducing this on the latest version again? preferably in singleplayer, but any type is fine. please attach a mclogs link too! thanks

**Comment by Hlebuw3k** [comment] 2024-09-19 01:16
https://mclo.gs/WGBzsDD
![2024-09-19_04 12 30](https://github.com/user-attachments/assets/357ba154-a8c7-4451-9c43-4300b61ed269)

**Comment by mrbuilder1961** [comment] 2024-09-21 05:15
fixed in my testing, plz confirm with the not -dev jar here: https://github.com/mrbuilder1961/ChatPatches/actions/runs/10970016503/artifacts/1961132983

**Closed as completed** 2024-09-24 00:17 UTC
Labels: bug, compatibility
