### ISSUE TITLE
Issue: Can't disable "Name text"

### ISSUE THREAD

**Issue by Ovbi-UwU** [mrbuilder1961/WheresMyChatHistory#10] opened 2022-05-17 20:31 UTC
I updated to 1.18.2 (Fabric [WMCH-1.18.2-1.4.4]), joined a multiplayer server and there I see _this_...

![Screenshot_195](https://user-images.githubusercontent.com/105749736/168902443-883b18ea-0153-4b6d-9538-87e71b0261ef.png)

I have tried removing/editing "**_Name text_**" but it was still this way (double nicks or huge **SYSTEM** text) + removing "**_$_**" is impossible because mod automatically adds it back...

Will it be fixed or maybe "**_Name text on/off button_**" added?
_(another option is that I'm just dumb and don't know how to make it work properly)_

**_PS Great mod <3_**

**Comment by Otifus** [comment] 2022-05-18 07:54
I aggre, i would also like to be able to disable this feature for playing on a multiplayer server, hope the author will add this feature

**Comment by mrbuilder1961** [comment] 2022-05-18 12:02
Yeah the SYSTEM name is a bug, I'm just going to remove it. I think i will add an option to disable it because it seems to break on a lot of servers, but for now can you try setting the name text to `<$>` and see if that does anything?

**Comment by Otifus** [comment] 2022-05-18 17:23
> Yeah the SYSTEM name is a bug, I'm just going to remove it. I think i will add an option to disable it because it seems to break on a lot of servers, but for now can you try setting the name text to `<$>` and see if that does anything?
![test](https://user-images.githubusercontent.com/104933617/169102624-2f27e54f-606b-4bd8-ba39-108edc4e1233.png)
unfortunately no change.
nicknames are still duplicated, and there is also this huge "SYSTEM" in the chat
1-it's message with `<$>`
2-with `$`
and number 3, this is a message symbol in global chat, it should be yellow but with the mod enabled it is white, 
as if missing a `&r` function after the mod text, which affects for global symbol color

**Comment by mrbuilder1961** [comment] 2022-05-18 18:09
the discoloration is probably because of the broken name string.
i think i'll try disabling the name string formatter if it fails so it doesn't add anything as opposed to always adding something.

so for a quick poll, if i try to fix it and if it doesn't work would it be better if I:
- added a toggle to disable the name string entirely
- added a config list of servers to disable the name string on

**Comment by Otifus** [comment] 2022-05-18 18:18
Personally, I would prefer the first option `toggle disable`

**Comment by Ovbi-UwU** [comment] 2022-05-18 19:52
Yeah, first option is much better

**Comment by mrbuilder1961** [comment] 2022-05-20 01:50
Okay so the bug seems to be fixed on my end, however I'm still working on the next major update so would you rather me:
1. Wait until the next full update is released for the bugfix
or
2. Have me release the bugfix with some unfinished/not working features (they just wont do anything)

**Comment by Otifus** [comment] 2022-05-20 07:57
a rather difficult choice, since we don't know how long it will take to complete new features, if it is days, a week, maybe two, then i would probably prefer to wait for a full update, if the release time is rather uncertain, or long enough, then maybe i would prefer to release beta version with unfinished features and bug fixes

**Comment by mrbuilder1961** [comment] 2022-05-20 13:25
Okay i'll give it a day or two and if i'm still not done with the update then i can release the bug fix only.

**Comment by Otifus** [comment] 2022-05-20 13:31
ok, we will wait for the update, thank you very much ^^

**Comment by mrbuilder1961** [comment] 2022-05-23 16:43
[This should be fixed](https://github.com/mrbuilder1961/WheresMyChatHistory/releases/tag/1.4.5-1.18.x), I tested it multiple times in different environments and I couldn't reproduce it anymore. Feel free to reopen this if there are still any problems.

**Closed as completed by mrbuilder1961** 2022-05-23 16:43 UTC
Labels: bug
