### ISSUE TITLE
Box text after game launch - Fabric 201.5.5

### ISSUE THREAD

**Issue by aladairmaxwell** [mrbuilder1961/WheresMyChatHistory#146] opened 2024-02-03 10:33 UTC
### Description
When I launch Minecraft, sometimes it has broken symbols, showing these squares.

### How to reproduce
I was thinking it comes from font resourcepack I've been using, but it can happen or not happen randomly, even without resourcepack. This error can be fixed only if you launch Minecraft and there was already installed pack, so you can disable it.

### Expected result
I want to see Minecraft work normally without this random squares.

### Log file link
https://api.mclo.gs/1/raw/8XiuFID

### Specs and Details
Required information:
- Windows 11
- 201.5.5
- Fabric 0.15.6, API 0.91.0
- YetAnotherConfigLib 3.2.1, Mod Menu 7.2.2
- List of all installed mods

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`)

### Additional context
Installed chat patches instead of that big list of different chat mods and this error started to happen.

[chatpatches.json](https://github.com/mrbuilder1961/ChatPatches/files/14151063/chatpatches.json)
ets/69295711/a16e79e2-5642-40d6-9d7f-81e76bfd959e)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/69295711/66e8f2e3-7aa0-4ba1-97af-00b37ac7207a)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/69295711/2d04c05c-8c4c-496f-a09f-f2be8ab02ffc)

**Comment by mrbuilder1961** [comment] 2024-02-03 18:40
right off the bat after clicking on the log i got this warning, have you tried resolving this first? caxton is a text overhaul mod so it could very easily be caused by that.
![image](https://github.com/mrbuilder1961/ChatPatches/assets/66807297/d5f4f5f3-47e0-456d-947e-10d41d5789ac)

**Comment by aladairmaxwell** [comment] 2024-02-03 22:39
Yes, I've already removed it and my error happened even before installing Caxton (i forgot to remove it when sent all the data here)

**Comment by mrbuilder1961** [comment] 2024-02-04 17:27
oh okay weird. could you send an updated log file then, please?

**Comment by aladairmaxwell** [comment] 2024-02-04 17:36
https://mclo.gs/YytlBLS

**Comment by mrbuilder1961** [comment] 2024-02-04 19:48
could you also send a log file without chat patches (and without the error)?

**Comment by aladairmaxwell** [comment] 2024-02-04 20:20
Okay, here is log with all mods installed - https://mclo.gs/Y7SV9EV

And here is log without mods Chat Patches, SPWN and SPWP - https://mclo.gs/ZZswgQy

I found out that these three are messing with each other for some reason. Maybe here lies a solution?

**Comment by mrbuilder1961** [comment] 2024-02-05 02:12
> Okay, here is log with all mods installed - https://mclo.gs/Y7SV9EV

This log doesn't have Chat Patches installed. Did you mean this one: https://mclo.gs/YytlBLS?

> And here is log without mods Chat Patches, SPWN and SPWP - https://mclo.gs/ZZswgQy
> I found out that these three are messing with each other for some reason. Maybe here lies a solution?

Can you link the sites where you got those two other mods? Then I can look through them.

**Comment by aladairmaxwell** [comment] 2024-02-05 08:16
Sure thing!
https://modrinth.com/mod/spwn
https://modrinth.com/mod/spwp

**Comment by mrbuilder1961** [comment] 2024-02-05 17:28
that's really weird, nothing is jumping out at me about this issue. i'll investigate when i can.

**Comment by mrbuilder1961** [comment] 2024-02-07 00:51
i really have no idea why this would be caused by chat patches at all, but assuming it still is could you try clearing your chat log and resetting (or just moving elsewhere) the config ? 

if it still persists after this, and after making sure all your other mods are up to date, i'll try and find more info. 

when i tested using the core mods listed at the beginning of this issue plus SPWP and SPWN, i couldn't recreate the issue.

**Comment by aladairmaxwell** [comment] 2024-02-07 18:11
After steps I reproduced from you, the issue still persists. I moved away chatpatches config and cleared chat log. What should I do next?

**Comment by mrbuilder1961** [comment] 2024-02-07 22:10
i'm not sure yet, i'll get back to you if i need anything else. in the meantime i'm going to see what causes this and figure it out when i can.

**Comment by mrbuilder1961** [comment] 2024-02-08 00:06
also, i would probably just remove chat patches while this is happening. but does this happen to all text or just the main menu screen? and if there is any other way to verify this isn't caused by chat patches i ask you to please try, i'm still very in awe how this is even remotely related.

**Comment by aladairmaxwell** [comment] 2024-02-08 09:20
Yes, the whole text in game breaks

**Comment by mrbuilder1961** [comment] 2024-08-09 00:21
is this still present in 201.5.6? either way i don't think chat patches has anything to do with this, maybe try using spwp and spwn without chat patches and see if it stays. if it's none of those, it must just be a weird issue with your texture pack, maybe edit or re-make the `pack.mcmeta` file or the `ascii.png` glyph map.

i hate to be so dismissive but i genuinely don't have and never had any code that would impact text rendering on this scale.

**Comment by mrbuilder1961** [comment] 2024-12-05 14:38
closing for lack of info, feel free to reopen if you're still experiencing it in the latest mod version.

**Closed as not planned** 2024-12-05 14:38 UTC
Labels: bug, awaiting info, compatibility
