### ISSUE TITLE
Incompatible with Distant Horizons mod

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#176] opened 2024-06-10 17:13 UTC
### Description
When loading minecraft, loading gets stuck

### How to reproduce
Download Distant Horizons and launch. 

### Expected result
To load in

### Log file link
https://mclo.gs/jRxO58y

### Specs and Details
Required information:
- Computer OS: macOS 
- Mod version: 204.6.5
- Fabric and API versions: 0.15.11 and 0.100.0+1.20.6
- YetAnotherConfigLib: 3.4.4+1.20.6-fabric and Mod Menu: 10.0.0-beta.1 
- List of all installed mods (can be a list *copied* from a log file **OR** a screenshot of the mods folder)
chatpatches-206.6.5.jar
cloth-config-14.0.126-fabric.jar
DistantHorizons-2.1.0-a-1.20.6-noForge.jar
fabric-api-0.100.0+1.20.6.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
ferritecore-6.1.1-fabric.jar
indium-1.0.30+mc1.20.4.jar
iris-1.7.0+mc1.20.6.jar
lithium-fabric-mc1.20.6-0.12.3.jar
modmenu-10.0.0-beta.1.jar
sodium-fabric-0.5.8+mc1.20.6.jar
YetAnotherConfigLib-3.4.4+1.20.6-fabric.jar

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
Anything else that could possibly be relevant to this issue. For example, what happened leading up to the incident.

**Comment by mrbuilder1961** [comment] 2024-06-17 03:55
thanks for the report, not sure what chat patches could be doing here bc it says its a fatal OpenGL error, but ill try and reproduce

**Comment by mrbuilder1961** [comment] 2024-06-24 22:15
is this still an issue when chat patches is installed? i had my friend try and reproduce the bug on 1.20.4 and it didn't have an issue... i know they're different but i dont think its related to chat patches at all

**Comment by Aces-and-Jacks** [comment] 2024-06-25 01:43
https://mclo.gs/g0j9WKC

https://github.com/mrbuilder1961/ChatPatches/assets/106651342/5786c4d6-111f-4ad7-84e6-4c97df4090d2

**Comment by Aces-and-Jacks** [comment] 2024-06-25 01:44
maybe it's OS...?

**Comment by Aces-and-Jacks** [comment] 2024-06-25 01:57
https://mclo.gs/qFplNWU

https://github.com/mrbuilder1961/ChatPatches/assets/106651342/087058ef-9daf-4493-9d25-8447f527256e

**Comment by Aces-and-Jacks** [comment] 2024-06-27 01:13
> thanks for the report, not sure what chat patches could be doing here bc it says its a fatal OpenGL error, but ill try and reproduce

`This GPU doesn't support Buffer Storage (OpenGL 4.4), falling back to using other methods` if you meant this it switches to another method so I don't think this is it. And `########## GL ERROR ##########` looked like it was testing which OpenGL versions worked. Chat patches works without distant horizons, and distant horizons works without chat patches. So I don't think it's an OpenGL error...tho I don't really know what

**Comment by mrbuilder1961** [comment] 2024-06-27 23:57
okay just ran this on 1.20.6 with just chat patches, yacl, fapi, and modmenu and it worked fine.
i did the same thing but with your exact modset and it was also fine.

im thinking this is a macos issue somehow, although i genuinely don't know what could be triggering this. sorry for the inconvenience :(

**Comment by Aces-and-Jacks** [comment] 2024-06-27 23:59
It's fine. So it's something related to Mac and the two mods. Both work fine alone but together they clash

**Comment by Aces-and-Jacks** [comment] 2024-06-28 00:04
Maybe fuz on lunapixel may have advice on it since he works with Mac. Or the creator of distance horizons since the mods conflict. I could try and make an issue there later if you want

**Comment by mrbuilder1961** [comment] 2024-06-28 15:49
yeah if you have time that'd be amazing! there's also another issue, #119, that is unrelated but also seems to be a macos issue so there's a chance they're related somehow

**Comment by Aces-and-Jacks** [comment] 2024-06-29 05:04
made it [Gitlab #729](https://gitlab.com/jeseibel/distant-horizons/-/issues/729)

**Comment by mazgaoten** [comment] 2024-09-10 23:50
i am seeing a similar issue on windows 11
chatpatches 210,6,5,1 and DH 2.2.1-a

both work find separately, as soon as both are on, it takes upwards of 2 minutes to get into a world from the selection screen.

minecraft itself loads quick, but when loading the worlds, it hangs

**Comment by mrbuilder1961** [comment] 2024-09-11 00:25
> i am seeing a similar issue on windows 11 chatpatches 210,6,5,1 and DH 2.2.1-a
> 
> both work find separately, as soon as both are on, it takes upwards of 2 minutes to get into a world from the selection screen.
> 
> minecraft itself loads quick, but when loading the worlds, it hangs

can you try disabling the chat log and seeing if that fixes your issue? also, please try the latest version that just released and after trying, send a log on https://mclo.gs!! ty

**Comment by mazgaoten** [comment] 2024-09-11 00:53
disabling the chat log fixed it went from 2 minutes of waiting to about 12 seconds

now that the log is gone, it seems to load fast.

loaded a backup of the log and disabled DH, and it still is slow to load. apparently DH is not the problem, just loading the log. 

apologize for that. the log is nice, but totally not needed, i think i'll just turn it off. (is there a way to set a limit? 

i only recently remember this happening, was there a change to the log reading/

do you still want to see the log? is there a specific thing?
here is the relavent area for the pause

`[17:34:20] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[17:34:20] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[17:34:20] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[17:34:20] [Render thread/INFO]: Started 10 worker threads
[17:34:20] [Render thread/INFO]: [ChatLog.deserialize] Reading...
[17:36:33] [Render thread/INFO]: [ChatLog.deserialize] Read the chat log containing 14537 messages and 1743 sent messages from AppData\Roaming\PrismLauncher\instances\1.21\.minecraft\logs\chatlog.json' in 132.866 seconds
[17:36:33] [Render thread/INFO]: [ChatLog.restore] Restored 14537 messages and 1743 history messages from 'AppData\Roaming\PrismLauncher\instances\1.21\.minecraft\logs\chatlog.json' into Minecraft!
[17:36:33] [Render thread/INFO]: [System] [CHAT] Â§8[Â§rggsmpÂ§8]
[17:36:33] [Render thread/INFO]: Client on ClientOnly mode connecting.
[17:36:33] [Render thread/INFO]: Started DhWorld of type Client_Only`

**Comment by mrbuilder1961** [comment] 2024-09-11 13:21
> apparently DH is not the problem, just loading the log.

yep, sounds like you're dealing with #191. you can toggle the chat log altogether in the config, or you can decrease your max message amount to a much lower number (say maybe 500-1000)

**Comment by mazgaoten** [comment] 2024-09-11 15:05
sure does. i assumed it was with DH, i don't know why. thanks though, i'll report in that thread :)

thank you!

**Comment by Aces-and-Jacks** [comment] 2024-11-03 20:59
Alright, the build hasn't been released yet but a nightly build of Distant Horizons on their discord fixes the issue. Since it hasn't been released yet I'm not sure if this should be closed

**Comment by mrbuilder1961** [comment] 2024-11-03 23:26
i'm just going to close it and if any confusion arises we can point to your comment. thanks for the update!

**Closed as completed** 2024-11-03 23:26 UTC
Labels: bug, compatibility
